events{}

http {
    upstream backend{
      server service-a:8080;
      server service-b:8080;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
}
